---
- name: System preparation
  include_tasks: system_preparation.yaml

- name: Configuring the web server - NGINX + PHP + MariaDB + NodeJS
  include_tasks: web_server.yaml

- name: Installing Asterisk
  include_tasks: deploy_asterist.yaml

- name: Installing FreePBX
  include_tasks: deploy_frepbx.yaml