---
- name: Restart Firewalld
  service: 
    name: firewalld 
    state: restarted

- name: Started and Enabled NGINX
  service: 
    name: nginx 
    enabled: true 
    state: started
    
- name: Disable httpd
  service: 
    name: httpd
    enabled: false
    state: stopped

- name: Restart NGINX
  service: 
    name: nginx 
    state: restarted      